version: '3.9'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env.docker
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: college_schedule
      MYSQL_USER: college_user
      MYSQL_PASSWORD: college_pass

    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
